
package com.mycompany.academico;

import javax.swing.JOptionPane;


public class VentanaPrincipal extends javax.swing.JFrame {
    
    int[] arrayMenores   ;
    int [] arrayMayores;
    int [] arrayAdultoMayor;
    
    int lonMenores = 0;
    int lonAdults = 0;
    int lonAdultMayor = 0;
    
    
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        search = new javax.swing.JButton();
        size = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("SISTEMA ACADEMICO");

        create.setBackground(new java.awt.Color(0, 204, 204));
        create.setForeground(new java.awt.Color(51, 51, 51));
        create.setText("Crear");
        create.setEnabled(false);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 204, 204));
        search.setForeground(new java.awt.Color(51, 51, 51));
        search.setText("Consultar");
        search.setEnabled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        size.setText("Tamaño");
        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(create)
                        .addGap(45, 45, 45)
                        .addComponent(search)
                        .addGap(47, 47, 47)
                        .addComponent(size)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(search)
                    .addComponent(size))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

       //Validar que cuando se digite una letra en una caja de texto que mande mensaje de, solamente numeros
        
        
        int im = 0; //contador de menores
        int ima = 0; //contador de mayores de edad
        int ad = 0; // contador de adultos mayores a 60 años
        
        //Bucle para llenar los arrays, falta mandar una validacion cuando
        while(im<arrayMenores.length || ima<arrayMayores.length || ad <arrayAdultoMayor.length){
            try{
                int age = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Diga su edad"));
                if (age < 18 && age > 0 && im < arrayMenores.length) {
                    JOptionPane.showInternalMessageDialog(rootPane, "Usted es menor de edad");
                    arrayMenores[im] = age;
                    im++;
                    if (im == arrayMenores.length) {
                        JOptionPane.showMessageDialog(rootPane, "Ya ha superado el limite de menores de edad");
                    }

                } else if ((age >= 18 && age < 60) && (ima < arrayMayores.length)) {
                    JOptionPane.showMessageDialog(rootPane, "Usted es mayor de edad");
                    arrayMayores[ima] = age;
                    ima++;
                    if (ima == arrayMayores.length) {
                        JOptionPane.showMessageDialog(rootPane, "Ya ha superado el limite de mayores de edad");
                    }

                } else if (age >= 60 && ad < arrayAdultoMayor.length) {
                    JOptionPane.showMessageDialog(rootPane, "Usted es adulto mayor");
                    arrayAdultoMayor[ad] = age;
                    ad++;
                    if (ad == arrayAdultoMayor.length) {
                        JOptionPane.showMessageDialog(rootPane, "Ya ha superado el limite de adultos mayores");
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error");
                }
            //Si yo quiero capturar cualquier tipo de excepcion, debo colocar Exception
            }catch(NumberFormatException e1){ //Como quiero solo capturar la excepcion de solo permitir numeros, entonces utilizo NumberFormatException
                JOptionPane.showMessageDialog(rootPane, "Error, solo se permite ingresar numeros");
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Ya ha superado el limite de todas las categorías");
        
    }//GEN-LAST:event_createActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
        //Mostrar los valores del array de menores
        String minors = "Menores de edad:  \n";
        for(int i=0 ;  i < arrayMenores.length; i++){
            minors += arrayMenores[i]+"\n";
        }
        
        //Mostrar los valores del array mayores de edad
        String adults = "Mayores de edad: \n";
        for(int i=0; i<arrayMayores.length;i++){
            adults += arrayMayores[i]+"\n";
        }
        
        //Mostrar los valores del array de adultos mayores
        String olderAdults = "Adultos mayores: \n";
        for(int i=0; i<arrayAdultoMayor.length;i++){
            olderAdults += arrayAdultoMayor[i] +"\n";
        }
        
        //Mostrar todos los arreglos en un cuadro de dialogo
        JOptionPane.showMessageDialog(rootPane, minors + "\n" + adults + "\n" + olderAdults);
    }//GEN-LAST:event_searchActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
        
        int lonMenores= Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese la longitud de menores"));
        int lonAdults= Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese la longitud de mayores"));
        int lonAdultMayor= Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese la longitud de adultos"));
        
        arrayMenores = new int[lonMenores];
        arrayMayores = new int[lonAdults];
        arrayAdultoMayor = new int[lonAdultMayor];
        
        create.setEnabled(true); //Habilitar el boton
        
    }//GEN-LAST:event_sizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton search;
    private javax.swing.JButton size;
    // End of variables declaration//GEN-END:variables
}
